version: "2"

services:
  honor-bracket:
    restart: no
    build: .
    volumes:
      - ./gatsby/public:/gatsby/public
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=honorspy-northdale-alliance.classicwowtools.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=honorspy-northdale-alliance.classicwowtools.com
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: root_default
