version: "2"

services:
  honor-build:
    restart: 'no'
    image: 'node'
    volumes:
      - ./public:/public
      - ./gatsby:/gatsby
      - ./exec.sh:/exec.sh
    command: bash /exec.sh
    environment:
      - NODE_ENV=production
  honor-server:
    restart: 'always'
    image: nginx
    depends_on:
      - honor-build
    volumes:
      - ./public:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=honorspy.classicwowtools.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=honorspy.classicwowtools.com
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: root_default
